### ISSUE TITLE
DropDownMenuKit error

### ISSUE THREAD

**Issue by shajeeamaan** [wayfinders/WRCalendarView#1]
i just download your project and run it after install pods but got an error.
it says "import DropDownMenuKit" <- no such a module.  how can fix that ?

**Comment by wayfinders** [comment]
1. go to Example folder of the downloaded source in terminal
2. pod install   (If you are not familiar with cocoapod, please visit https://cocoapods.org/ )
3. open WRCalendarView.xcworkspace
4. run 

If you still have problems, please let me know.
